# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: microsoft/dotnet:sdk
#image: squidex/aspnetcore-build-phantomjs:2.0.3-jessie
image: squidex/aspnetcore-build-phantomjs-chromium:2.0.3-jessie-fix1

pipelines:
  branches:
    master:
      - step:
          name: buildapp
          caches:
            - dotnetcore
          script: 
            - export PROJECT_NAME=Frontend/MusicStoreDemo.csproj
            - export TEST_NAME=Tests/MusicStoreDemo.Tests.csproj
            - dotnet restore
            - dotnet build $PROJECT_NAME
            - dotnet test $TEST_NAME
            - export PHANTOMJS_BIN=/usr/local/bin/phantomjs #/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
            - cd Frontend/ClientApp;  npm test